version: "2"
services:
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  logstash:
    build: logstash/
    depends_on:
      - kafka
      - elasticsearch
    volumes:
      - "$PWD/logstash.conf:/logstash.conf"
      - "$PWD/logstash_out.log:/logstash_out.log"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    volumes:
      - "$PWD/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
